FROM mirrors.tencent.com/tlinux/tlinux3.2-minimal:v20250107

ENV RUSTUP_DIST_SERVER=https://rsproxy.cn       \
  RUSTUP_UPDATE_ROOT=https://rsproxy.cn/rustup  \
  CARGO_HOME=/usr/local/cargo                   \
  RUSTUP_HOME=/usr/local/rustup                 \
  PATH=/usr/local/cargo/bin:$PATH

ARG DEFAULT_TOOLCHAIN=1.85.0 \
  PROFILE=default

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs           | \
  sh -s -- --default-toolchain $DEFAULT_TOOLCHAIN --profile $PROFILE -y

RUN dnf install -y clang git && dnf clean all


FROM rust:1.85.0-slim-bookworm AS rust

ENV RUSTUP_DIST_SERVER="https://rsproxy.cn" \
  RUSTUP_UPDATE_ROOT="https://rsproxy.cn/rustup"

RUN sed -i 's/deb.debian.org/mirrors.tencent.com/g' /etc/apt/sources.list.d/debian.sources  &&\
  sed -i 's|security.debian.org/debian-security|mirrors.tencent.com/debian-security|g'      \
    /etc/apt/sources.list.d/debian.sources

RUN apt update && apt install -y wget

# 下载并添加 GPG 密钥
# 添加 LLVM 18 的 APT 源（Debian 12 代号为 bookworm）
RUN wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/llvm.asc &&\
  echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-18 main" | tee /etc/apt/sources.list.d/llvm-18.list

# libssl-dev 和 pkg-config 是 cargo-component 的依赖
# clang 是 mold 链接器的依赖
RUN apt update                                          &&\
  apt install -y clang-18 lldb-18 libssl-dev pkg-config &&\
  apt install -y git vim make                           &&\
  apt clean                                             &&\
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN ln -sf `which clang-18` /usr/bin/clang && ln -sf `which lldb-18` /usr/bin/lldb 

RUN rustup component add rustfmt && rustup target add wasm32-unknown-unknown wasm32-wasip1 wasm32-wasip2


FROM busybox:1.36.1 AS wasmtime

ARG WASMTIME_VERSION

ENV REPO_URL=https://github.com/bytecodealliance/wasmtime/releases/download/v$WASMTIME_VERSION

RUN wget $REPO_URL/wasmtime-v$WASMTIME_VERSION-x86_64-linux.tar.xz

RUN mkdir -p /output && tar -C /output --strip-components 1 -Jxvf wasmtime-v$WASMTIME_VERSION-x86_64-linux.tar.xz

WORKDIR /output/adapter-modules

RUN wget $REPO_URL/wasi_snapshot_preview1.command.wasm  &&\
  wget $REPO_URL/wasi_snapshot_preview1.proxy.wasm      &&\
  wget $REPO_URL/wasi_snapshot_preview1.reactor.wasm


FROM rust

ENV PATH=/opt/wasmtime:$PATH

COPY --from=wasmtime /output /opt/wasmtime
